// <auto-generated />
using System;
using CommonlibDAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonlibDAO.Migrations
{
    [DbContext(typeof(DBContextEFCore))]
    [Migration("20260213122440_BaseSchema")]
    partial class BaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonlibDAO.Modles.Employee_History.tbl_EMP_History", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<int?>("EmpTypeID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time");

                    b.Property<string>("StrInTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StrOutTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("allow_proxy_attendance")
                        .HasColumnType("bit");

                    b.Property<DateTime>("changed_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<int>("designation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("email_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("location_id")
                        .HasColumnType("int");

                    b.Property<string>("phone_number")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("reports_to_employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("section_id")
                        .HasColumnType("int");

                    b.Property<int?>("work_location_type_id")
                        .HasColumnType("int");

                    b.HasKey("history_id");

                    b.ToTable("tbl_EMP_History");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Employee_History.tbl_EMP_TransferHistory", b =>
                {
                    b.Property<int>("TransferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferID"));

                    b.Property<int?>("changed_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("changed_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("new_department_id")
                        .HasColumnType("int");

                    b.Property<int?>("new_designation_id")
                        .HasColumnType("int");

                    b.Property<int?>("new_reports_to_employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("new_section_id")
                        .HasColumnType("int");

                    b.Property<int?>("old_department_id")
                        .HasColumnType("int");

                    b.Property<int?>("old_designation_id")
                        .HasColumnType("int");

                    b.Property<int?>("old_reports_to_employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("old_section_id")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TransferID");

                    b.ToTable("tbl_EMP_TransferHistory");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Employee_History.tbl_EmployeeReportingHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<int>("changed_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("changed_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("new_reports_to_employee_id")
                        .HasColumnType("int");

                    b.Property<int>("old_reports_to_employee_id")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("history_id");

                    b.ToTable("tbl_EmployeeReportingHistory");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Employee_History.tbl_PEER_EMP_Mapping", b =>
                {
                    b.Property<int>("Peer_Mapping_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Peer_Mapping_ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EMP_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Peer_EMP_ID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("Peer_Mapping_ID");

                    b.ToTable("tbl_PEER_EMP_Mapping");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.FR_System.tbl_EMP_FRS_History", b =>
                {
                    b.Property<int>("History_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("History_ID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte?>("FRSStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("FRS_ID")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.HasKey("History_ID");

                    b.ToTable("tbl_EMP_FRS_History");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.FR_System.tbl_EMP_FRS_Registration", b =>
                {
                    b.Property<int>("FRS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FRS_ID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("FRSStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.HasKey("FRS_ID");

                    b.ToTable("tbl_EMP_FRS_Registration");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.FR_System.tbl_FAC_Dtls", b =>
                {
                    b.Property<int>("FAC_Mapping_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAC_Mapping_ID"));

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Section_ID")
                        .HasColumnType("int");

                    b.HasKey("FAC_Mapping_ID");

                    b.ToTable("tbl_FAC_Dtls");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.FR_System.tbl_FRS_Key", b =>
                {
                    b.Property<int?>("keyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("keyID"));

                    b.Property<string>("KeyValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keyname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("keyID");

                    b.ToTable("tbl_FRS_Key");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Client", b =>
                {
                    b.Property<int>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("client_id"));

                    b.Property<string>("address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("client_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("contact_email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("contact_phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.HasKey("client_id");

                    b.ToTable("tbl_Client");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("department_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("department_id");

                    b.ToTable("tbl_Department");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Designation", b =>
                {
                    b.Property<int>("designation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("designation_id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<string>("designation_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_hod")
                        .HasColumnType("bit");

                    b.Property<int?>("reports_to_designation_id")
                        .HasColumnType("int");

                    b.Property<int?>("section_id")
                        .HasColumnType("int");

                    b.HasKey("designation_id");

                    b.ToTable("tbl_Designation");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Dist", b =>
                {
                    b.Property<int>("D_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_ID"));

                    b.Property<string>("D_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("D_ID");

                    b.ToTable("tbl_Dist");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_EMP_Type", b =>
                {
                    b.Property<int>("EmpTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpTypeID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMPType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("client_id")
                        .HasColumnType("int");

                    b.HasKey("EmpTypeID");

                    b.ToTable("tbl_EMP_Type");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<int?>("D_ID")
                        .HasColumnType("int");

                    b.Property<int?>("EmpTypeID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time");

                    b.Property<string>("StrInTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StrOutTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("allow_proxy_attendance")
                        .HasColumnType("bit");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<int>("designation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("email_id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<int?>("location_id")
                        .HasColumnType("int");

                    b.Property<string>("phone_number")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("reports_to_employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("section_id")
                        .HasColumnType("int");

                    b.Property<int?>("work_location_type_id")
                        .HasColumnType("int");

                    b.HasKey("employee_id");

                    b.HasIndex("reports_to_employee_id");

                    b.ToTable("tbl_Employee");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Location", b =>
                {
                    b.Property<int>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("location_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("location_id");

                    b.ToTable("tbl_Location");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Section", b =>
                {
                    b.Property<int>("section_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("section_id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<string>("section_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("section_id");

                    b.ToTable("tbl_Section");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_WorkLocationType", b =>
                {
                    b.Property<int>("work_location_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("work_location_type_id"));

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("work_location_type_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("work_location_type_id");

                    b.ToTable("tbl_WorkLocationType");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("company_id");

                    b.ToTable("tbl_company");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Meetings_Fields_Tours.tbl_EmpMeetings", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfMeeting")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MeetingTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ToTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.HasKey("MeetingId");

                    b.ToTable("tbl_EmpMeetings");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Meetings_Fields_Tours.tbl_Emp_FieldVisits", b =>
                {
                    b.Property<long>("FieldVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FieldVisitID"));

                    b.Property<int>("Client_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FieldVisitID");

                    b.ToTable("tbl_Emp_FieldVisits");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Meetings_Fields_Tours.tbl_MeetingTypes", b =>
                {
                    b.Property<int>("MeetingTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingTypeID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MeetingTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MeetingTypeID");

                    b.ToTable("tbl_MeetingTypes");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Meetings_Fields_Tours.tbl_ModeOfTravel", b =>
                {
                    b.Property<int>("ModeOfTravelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeOfTravelID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModeOfTravelID");

                    b.ToTable("tbl_ModeOfTravel");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Meetings_Fields_Tours.tbl_TourTypes", b =>
                {
                    b.Property<int>("TourTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourTypeID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TourTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TourTypeID");

                    b.ToTable("tbl_TourTypes");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Support.tbl_DeactivateReasons", b =>
                {
                    b.Property<int>("DeactivateReason_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeactivateReason_ID"));

                    b.Property<string>("DeactivateReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeactivateReason_ID");

                    b.ToTable("tbl_DeactivateReasons");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.Support.tbl_PostContactSupport", b =>
                {
                    b.Property<int>("supportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supportID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Issue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.HasKey("supportID");

                    b.ToTable("tbl_PostContactSupport");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.User_Security.tbl_HODLevel", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"));

                    b.Property<string>("HODLevel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("tbl_HODLevel");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.User_Security.tbl_Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId");

                    b.ToTable("tbl_Roles");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.User_Security.tbl_UserLogin", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<int?>("employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("failed_attempts")
                        .HasColumnType("int");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_failed_attempt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("lockout_until")
                        .HasColumnType("datetime2");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("user_id");

                    b.ToTable("tbl_UserLogin");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfAttend")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time");

                    b.Property<string>("InTime_Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InTime_longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time");

                    b.Property<string>("OutTime_Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OutTime_longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int?>("marked_by_employee_id")
                        .HasColumnType("int");

                    b.HasKey("AttendanceID");

                    b.ToTable("tbl_Attendance");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_Attendance_Extra", b =>
                {
                    b.Property<int>("ExtraTimeAttendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraTimeAttendID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfAttend")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InTime_Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InTime_Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutTime_Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OutTime_Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TypeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("place")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ExtraTimeAttendID");

                    b.ToTable("tbl_Attendance_Extra");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_EMP_NotAttendedOffice", b =>
                {
                    b.Property<int>("NotAttendedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotAttendedID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("ModeOfTravelID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Place")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("SubTypeOfNotAttende")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalDays")
                        .HasColumnType("int");

                    b.Property<byte>("TypeOfNotAttende")
                        .HasColumnType("tinyint");

                    b.HasKey("NotAttendedID");

                    b.ToTable("tbl_EMP_NotAttendedOffice");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_Holiday", b =>
                {
                    b.Property<int>("holiday_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("holiday_id"));

                    b.Property<int?>("client_id")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("holiday_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("holiday_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_public")
                        .HasColumnType("bit");

                    b.HasKey("holiday_id");

                    b.ToTable("tbl_Holiday");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_LeaveTypes", b =>
                {
                    b.Property<int>("LeaveTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LeaveTypeID");

                    b.ToTable("tbl_LeaveTypes");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_NotAttendSubType", b =>
                {
                    b.Property<int>("NotAttendSubTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotAttendSubTypeID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotAttendSubTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeOfNotAttend")
                        .HasColumnType("int");

                    b.HasKey("NotAttendSubTypeID");

                    b.ToTable("tbl_NotAttendSubType");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.tbl_Notifications", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime?>("Createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("NotificationID");

                    b.ToTable("tbl_Notifications");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Employee", b =>
                {
                    b.HasOne("CommonlibDAO.Modles.MasterTables.tbl_Employee", "ReportsToEmployee")
                        .WithMany("Subordinates")
                        .HasForeignKey("reports_to_employee_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReportsToEmployee");
                });

            modelBuilder.Entity("CommonlibDAO.Modles.MasterTables.tbl_Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
